# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- development

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '2c474437-f315-4009-a58e-b050a9e960f8'

  resourceGroupName: 'test123123123123123'
  
  # Web app name
  webAppName: 'test123123123123123'
  
  # Environment name
  environmentName: 'test123123123123123'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool: 
      vmImage: $(vmImageName)
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - bash: |
        npm install
        npm run build --if-present
        npm run test --if-present
      displayName: 'npm install, build and test'
    - bash: npm prune --production
      displayName: 'Remove dev packages'
      condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
      artifact: drop
